baseurl             = "https://husnabeauty.netlify.com/"
languageCode        = "en-us"
title               = "HusnaBeauty"
theme               = "introduction"
enforce_ssl         = "your-url.com"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
layoutdir           = "layouts"
publishdir          = "public"
# disqusshortname   = "xxx" # Enable Disqus for comments
# googleAnalytics   = "xxx"

[permalinks]
fixed = ":title/"
blog  = "blog/:slug/"

[params]
author        = "Khalidah Alhusna" # Full name shows on blog post pages
firstname     = "Alhusna" # First name shows in introduction on main page
tagline       = "Hi, I'm Khalidah Alhusna Kamilen!" # Appears after the introduction
avatar        = "img/husna.jpg" # Path to image in static folder eg. img/avatar.png
email         = "khalidahusna97@ymail.com" # Shows in contact section, or leave blank to omit
dateform      = "Jan 2, 2006"
dateformfull  = "Mon Jan 2 2006 15:04:05 EST"
cachebuster   = true # Add the current unix timestamp in query string for cache busting css assets
description   = "Website Description"
faviconfile   = "img/fav.ico"
highlightjs   = true # Syntax highlighting
lang          = "en"
footertext    = "" # Text to show in footer (overrides default text)

# Social icons appear in introduction and contact section. Input your username only, eg "you" as it appears in "twitter.com/you"
linkedin      = ""
twitter       = "crabbybyruni"
github        = ""
codepen       = ""
pinterest     = ""
facebook      = "byruni.husna"
googleplus    = "102238963582710753994"
instagram     = "husnabeauty.health"
whatsapp      = "601133147038"

showblog        = true # Show Blog section on home page
showallposts    = false # Set 'true' to list all posts on home page, or set 'false' to link to separate blog list page
showlatest      = true # Show latest blog post summary
sharebuttons    = true # On post pages, show share this social buttons

showprojects    = true # Show Projects section on home page

# This is your projects section. Three images of the same dimensions will look the nicest. If images are omitted, text links will be shown.
project1link    = "#"
project1img     = "img/aflalfa.jpg"
project1title   = "ALFALFA COMPLEX"

project2link    = "#"
project2img     = "img/vivix.jpg"
project2title   = "VIVIX"

project3link    = "#"
project3img     = "img/lecithin.jpg"
project3title   = "LECHITHIN"
